// <auto-generated />
using System;
using Firebird.Embedded.AspNetCore.Data;
using FirebirdSql.EntityFrameworkCore.Firebird.Metadata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Firebird.Embedded.AspNetCore.Migrations.Data
{
    [DbContext(typeof(DataDbContext))]
    partial class DataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 31);

            modelBuilder.Entity("Firebird.Embedded.AspNetCore.Data.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR(256)");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRegularStudent")
                        .HasColumnType("BOOLEAN")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = "becaf884-4f6a-4529-9612-2d07c4ff10fe",
                            Age = 30,
                            IsRegularStudent = false
                        },
                        new
                        {
                            Id = "13f014fc-3c8b-43e8-b7ec-e4c12fc4294d",
                            Age = 25,
                            IsRegularStudent = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
